default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10000
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    normalize: false
    num_epoch: 5
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false

BrainWallJumpCC:
    max_steps: 2.0e5
    num_layers: 2
    beta: 5.0e-4
    hidden_units: 256
    use_recurrent: true
    sequence_length: 32
    time_horizon: 32
    batch_size: 32
    buffer_size: 320

Ball3DBrainR:
    summary_freq: 1000
    normalize: true
    # batch_size: 1000
    # buffer_size: 10000
    hidden_units: 64
    max_steps: 1.0e4
    time_horizon: 32
    batch_size: 32
    buffer_size: 320
    sequence_length: 32
    use_recurrent: true


Ball3DHardBrain:
    max_steps: 5.0e4
    num_layers: 2
    normalize: true
    num_epoch: 3
    beta: 5.0e-4
    hidden_units: 64
    use_recurrent: true
    sequence_length: 8
    time_horizon: 8
    batch_size: 32
    buffer_size: 320

HallwayBrainDC:
    num_layers: 3
    hidden_units: 256
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 512
    batch_size: 64
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

BrainWallJumpDC:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 16
    batch_size: 2
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

HallwayBrainDCLSTM:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 16
    batch_size: 2
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64

HallwayBrainCC:
    max_steps: 5.0e4
    num_layers: 2
    normalize: false
    num_epoch: 5
    beta: 5.0e-4
    hidden_units: 128
    use_recurrent: false
    sequence_length: 32
    time_horizon: 64
    #batch_size: 1024
    #buffer_size: 5120
    batch_size: 1024
    buffer_size: 10240

GridWorldBrain:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 256
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 5

BasicBrain:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 20
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 2000
    time_horizon: 3

StudentBrain:
    trainer: imitation
    max_steps: 10000
    summary_freq: 1000
    brain_to_imitate: ExpertBrain
    batch_size: 16
    batches_per_epoch: 10
    num_layers: 4
    hidden_units: 64
    use_recurrent: false
    sequence_length: 16
    buffer_size: 128
